@baseUrl = http://localhost:3000

### AppControllerGetHello
# @name UserControllerCreate
POST {{baseUrl}}/user
Content-Type: application/json

{
  "nome": "Gabriel Maranhão",
  "email": "gmacs2212@gmail.com",
  "password": "Gmac22122003.",
  "role": "admin"
}

